# Generated by Django 3.2.9 on 2021-12-10 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('Marque', models.CharField(max_length=100)),
                ('nbDisponible', models.IntegerField(null=True)),
                ('prix', models.FloatField(null=True)),
                ('image', models.ImageField(default=True, upload_to='')),
            ],
        ),
    ]
