# Generated by Django 3.2.9 on 2021-12-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
