# Generated by Django 3.2.9 on 2021-12-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_auto_20211214_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Marque',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='Nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='Type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='nbDisponible',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='prix',
            field=models.FloatField(null=True),
        ),
    ]
