# Generated by Django 3.2.9 on 2021-12-17 12:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_bon_etablissement_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon',
            name='Type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bon',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='Type',
            field=models.CharField(default='Tableau', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
