# Generated by Django 3.2.9 on 2021-12-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0006_auto_20211217_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon',
            name='Montant',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='Montant',
            field=models.FloatField(null=True),
        ),
    ]
