# Generated by Django 3.2.9 on 2021-12-17 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_auto_20211217_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bon',
            name='Facture',
        ),
        migrations.AddField(
            model_name='facture',
            name='Bons',
            field=models.ManyToManyField(to='Gestion.Bon'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='bon',
            name='Num',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='Nom',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Num',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
