# Generated by Django 3.2.9 on 2021-12-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0008_auto_20211217_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='Num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='Num',
            field=models.IntegerField(null=True),
        ),
    ]
