# Generated by Django 3.2.9 on 2021-12-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0009_auto_20211217_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='bon',
            name='paye',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='paye',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
