# Generated by Django 3.2.9 on 2021-12-17 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0010_auto_20211217_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='etablissement',
            name='Etat',
            field=models.CharField(default='endetté', max_length=100),
            preserve_default=False,
        ),
    ]
