# Generated by Django 3.2.9 on 2022-01-03 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0013_auto_20211218_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bon',
            name='Articles',
        ),
        migrations.AddField(
            model_name='articlebl',
            name='Bon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Gestion.bon'),
            preserve_default=False,
        ),
    ]
