# Generated by Django 3.2.9 on 2022-01-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0014_auto_20220103_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlebl',
            old_name='Article',
            new_name='article',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='Articles',
        ),
        migrations.AlterField(
            model_name='article',
            name='Nom',
            field=models.CharField(max_length=100),
        ),
    ]
