# Generated by Django 3.2.9 on 2022-01-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0015_auto_20220105_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlebl',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.article'),
        ),
    ]
