# Generated by Django 3.2.9 on 2022-01-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0016_alter_articlebl_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bon',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateField(),
        ),
    ]
